// book-kit — main entry
//
// Title page, copyright page, TOC, and front-matter. Chapter structure
// is delegated to chapters.typ which is generated by scripts/md-to-typst.mjs
// from BOOK.{pt-BR,en,es}.md. To rebuild everything:
// `bash scripts/build.sh` from the repo root.
//
// Language is selected at compile time via --input lang=pt, en or es.
// Every book-specific string comes from book.config.json (single source of
// truth) so this entry file stays generic and shareable across books.

#import "template.typ": book, part-page, toc-title, voice, mono, text-main, text-body, text-secondary, text-muted, amber-deep

#let lang = sys.inputs.at("lang", default: "pt")

// Book-specific strings live in book.config.json. The absolute path resolves
// against the Typst project root (--root, set by build.sh), so this works
// whether the engine is this repo or a git submodule.
#let cfg = json("/book.config.json")
#let author = cfg.author
#let L = cfg.languages.at(lang)

// ─── Copyright page (front matter) ──────────────────────────────────
// A bold title + subtitle header, then each paragraph from the config's
// copyright array, spaced apart. Authorship/rights come from the config.
#let copyright-body = [
  #strong(L.title) \
  #L.subtitle

  #v(1em)
  #for p in L.copyright [
    #p

    #v(0.6em)
  ]
]

#show: book.with(
  title: L.title,
  subtitle: L.subtitle,
  author: author,
  lang: lang,
  eyebrow: L.eyebrow,
  copyright-body: copyright-body,
  // Optional dedication / epigraph / … pages. Generated (possibly empty) by the
  // converter from frontmatter/*.md; rendered unnumbered before the TOC, and
  // never listed in it.
  frontmatter: include "/typst/frontmatter.typ",
)

// ─── Table of contents ──────────────────────────────────────────────
// Print-first outline: dark ink throughout, amber reserved for the part
// eyebrows only. Plain styled text (no link underlines to muddy the print),
// spaced so the structure reads in clear, uncramped sections. Part dividers
// are located via the <part-entry> metadata marker.
#toc-title(L.tocName)
#context {
  let items = query(heading.where(outlined: true).or(<part-entry>))
  let dropped-subtitle = false
  for it in items {
    let loc = it.location()
    let pg = counter(page).at(loc).first()
    if it.func() == metadata {
      // Part divider — the one coloured accent: a mono amber eyebrow over
      // the serif name, set off with air so the TOC breaks into sections.
      let info = it.value
      block(above: 1.5em, below: 0.8em, breakable: false)[
        #set par(justify: false, first-line-indent: 0pt, leading: 0.5em)
        #link(loc)[
          #text(font: mono, size: 7.5pt, fill: amber-deep, tracking: 0.18em, weight: 500)[#lower(info.label)]
          #linebreak()
          #text(font: voice, size: 13pt, fill: text-main, weight: 500)[#info.name]
        ]
        #h(1fr)
        #box(text(font: mono, size: 8pt, fill: text-muted)[#pg])
      ]
    } else {
      if it.level > 2 { continue }
      // The frontmatter subtitle is the first heading and already lives on
      // the title page — keep it out of the TOC.
      if not dropped-subtitle { dropped-subtitle = true; continue }
      let is-chapter = it.level == 1
      block(above: if is-chapter { 0.72em } else { 0.3em }, below: 0pt, breakable: false)[
        #set par(justify: false, first-line-indent: 0pt, leading: 0.55em)
        #pad(left: if is-chapter { 0pt } else { 1.5em })[
          #set text(
            size: if is-chapter { 10.5pt } else { 9.5pt },
            weight: if is-chapter { 500 } else { 400 },
            fill: if is-chapter { text-main } else { text-secondary },
          )
          #link(loc)[#it.body]
          #h(1fr)
          #box(text(font: mono, size: 8pt, fill: text-muted)[#pg])
        ]
      ]
    }
  }
}
// Start the book's opening (front matter) on its own page rather than jammed
// under the last TOC line.
#pagebreak(weak: true)

// ─── Generated structure (parts + chapter includes) ─────────────────
// chapters.typ is produced by the converter into the PROJECT (not the kit), so
// include it by absolute-from-root path — works whether this entry lives in the
// repo or a submodule. It lists every chapter in reading order, with part
// dividers between Part I / II / III / Appendices.
#include "/typst/chapters.typ"
